name: Release Executables Archivist
on:
  push:
    branches:
      - master
    paths:
      - src/Archivist/**
      - src/Epub/**
      - src/FileStorage/**
      - src/Images/**
      - src/ImgProj/**
      - src/**.props
  workflow_dispatch:
jobs:
  release-executables-archivist:
    uses: ./.github/workflows/release-executables.yml
    with:
      project: Archivist
      publish-args: "-p:EnableCompressionInSingleFile=true -p:PublishTrimmed=true -p:TrimmerSingleWarn=false"