name: Run Tests FileStorage
on:
  push:
    branches:
      - master
    paths:
      - src/FileStorage/**
      - src/FileStorage.Tests/**
      - src/Directory.Packages.props
  workflow_dispatch:
jobs:
  run-tests-epub:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: FileStorage
      dotnet-version: "7.0"