name: Run Tests Subprocesses
on:
  push:
    branches:
      - master
    paths:
      - src/Subprocesses/**
      - src/Subprocesses.Tests/**
      - src/**.props
  workflow_dispatch:
jobs:
  run-tests-subprocesses:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: Subprocesses