name: Run Tests Epub

on:
  push:
    branches:
      - master
    paths:
      - src/Epub/**
      - src/Epub.Tests/**
      - src/**.props
  workflow_dispatch:
jobs:
  run-tests-epub:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: Epub