name: Run Tests Subprocesses
on:
  push:
    branches:
      - master
    paths:
      - src/Subprocesses/**
      - src/Subprocesses.Tests/**
      - src/Directory.Packages.props
  workflow_dispatch:
jobs:
  run-tests-subprocesses:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: Subprocesses
      dotnet-version: "7.0"