name: Run Tests ImgProj
on:
  push:
    branches:
      - master
    paths:
      - src/ImgProj/**
      - src/ImgProj.Tests/**
      - src/**.props
  workflow_dispatch:
jobs:
  run-tests-imgproj:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: ImgProj