name: Run Tests ImgProj
on:
  push:
    branches:
      - master
    paths:
      - src/ImgProj/**
      - src/ImgProj.Tests/**
  workflow_dispatch:
jobs:
  run-tests-epub:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: ImgProj
      dotnet-version: "7.0"