name: Run Tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

env:
  DOTNET_VERSION: "7.0"
jobs:
  run-tests:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet test src/${{ inputs.project }}.Tests
        