name: Run Tests Epub

on:
  push:
    branches:
      - master
    paths:
      - src/Epub/**
      - src/Epub.Tests/**
  workflow_dispatch:
jobs:
  run-tests-epub:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: Epub
      dotnet-version: "7.0"