name: Run Tests Images
on:
  push:
    branches:
      - master
    paths:
      - src/Images/**
      - src/Images.Tests/**
  workflow_dispatch:
jobs:
  run-tests-images:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: Images
      dotnet-version: "7.0"